### ISSUE TITLE
Sample app or instructions for use ?

### ISSUE THREAD

**Issue by iangregsondev** [renew-app/nestjs-eventstore#2]
Hi,

Looks like a great library around the official eventstore library but for use on nestjs.

Do you have a sample application that uses the library or some detailed instructions?

Thanks in advance.

**Comment by natersgonnanate** [comment]
Hi @iangregsondev,

Thank you! As I'm sure you've seen, we're in the very early stages of standing up the library and we've yet to push much in the way of unit tests, and especially documentation. That said, I'll put together a more helpful readme as soon as I can with a basic sample application to follow. I'll update the issue, as well, when an update is available.

**Comment by iangregsondev** [comment]
Thanks @natersgonnanate , I will keep my eye out..

looks like a very interesting project.

Good luck.

**Comment by raarts** [comment]
Too bad this was stalled..
